"""Add title column to days table

Revision ID: b7aec6d8c64f
Revises: 
Create Date: 2025-09-25 11:08:08.563258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7aec6d8c64f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to create all tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('months',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('translation', sa.String(length=50), nullable=True),
        sa.Column('number', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_months_id'), 'months', ['id'], unique=False)

    op.create_table('books',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=True),
        sa.Column('author', sa.String(length=100), nullable=True),
        sa.Column('url', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)

    op.create_table('days',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('month_id', sa.Integer(), nullable=True),
        sa.Column('special_event', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['month_id'], ['months.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_days_id'), 'days', ['id'], unique=False)

    op.create_table('readings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('day_id', sa.Integer(), nullable=True),
        sa.Column('period', sa.String(length=20), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('author', sa.String(length=100), nullable=True),
        sa.Column('source_book', sa.String(length=200), nullable=True),
        sa.Column('page', sa.String(length=50), nullable=True),
        sa.Column('reference', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema to drop all tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_days_id'), table_name='days')
    op.drop_table('days')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_months_id'), table_name='months')
    op.drop_table('months')
    # ### end Alembic commands ###
